name: Create GitHub Release

inputs:
  full-version:
    description: "Version number (e.g. 1.2.3)"
    required: true
  build-file-path:
    description: "File path to the build zip"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Release
      id: create-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION="${{ inputs.full-version }}"
        TAG="v$VERSION"

        gh release create "$TAG" \
          ${{ inputs.build-file-path }} \
          --title "$TAG" \
          --notes "Release $TAG"